### ISSUE TITLE
Изменения в новой версии Telegram Desktop

### ISSUE THREAD

**Issue by 0z0sk0** [si6Och4j/tdata-decrypt#1]
![image](https://github.com/user-attachments/assets/3e09b17a-e00f-482c-ab44-d386fb2c9bbe)

Как минимум файл key_data, был переименован в key_datas.

[Класс TData](https://github.com/si6Och4j/tdata-decrypt/blob/4c5388fd7f6198da43795e519f109c0ce93ffe7b/tdata_decrypt/data.py#L87C13-L87C43) вероятно не сможет прочитать TDF ключи

**Comment by si6Och4j** [comment]
"s" всегда добавляется в конец всех TDF файлов, [тут видно](https://github.com/si6Och4j/tdata-decrypt/blob/4c5388fd7f6198da43795e519f109c0ce93ffe7b/tdata_decrypt/tdf.py#L33) (Зачем - хз).

Поставлю новую версию, проверю, но скорее всего всё будет работать

**Comment by si6Och4j** [comment]
Проверил на версии 5.8.2, всё ок
